apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "flaskapp"
  namespace: "default"
  labels:
    app: "flaskapp"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "flaskapp"
  template:
    metadata:
      labels:
        app: "flaskapp"
    spec:
      containers:
      - name: "mfadam786-virtualization-assignment-3-flaskapp"
        image: "gcr.io/virtualization-330121/virtualization-assignment-3-flaskapp:$SHORT_SHA"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "flaskapp"
  namespace: "default"
  labels:
    app: "flaskapp"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "flaskapp"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80